# -*- coding: utf-8 -*-
"""BTT AI Fall Studio - PIMCO 1C

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zRNAYZMMDzwO2luZ_dgArggYvacMeUhD
"""

import os
import pandas as pd
from bs4 import BeautifulSoup
from google.colab import drive

# Mount Google Drive to access files
drive.mount('/content/drive')

# Our data folder
data_folder = '/content/drive/MyDrive/data (1)'

# Get all files
files = os.listdir(data_folder)

# Keep only the HTM files
htm_files = [file for file in files if file.endswith('.htm')]

print("Total files:", len(files))
print("HTM files:", len(htm_files))
print("First 5 files:")
print(htm_files[:5])

# STEP 2: Extract text from all HTM files

data = []

for filename in htm_files:
    file_path = os.path.join(data_folder, filename)

    # Open the HTML file
    with open(file_path, 'r', encoding='utf-8') as file:
        html = file.read()

    # Convert HTML into readable text
    soup = BeautifulSoup(html, 'html.parser')
    text = soup.get_text(" ", strip=True)

    # Get basic information from the filename
    parts = filename.replace('.htm', '').split('_')

    data.append({
        'file_name': filename,
        'extracted_text': text
    })

print("Finished extracting text from", len(data), "files")

# STEP 3: Create our index table

df = pd.DataFrame(data)

print("Number of filings:", len(df))
print("Columns:", df.columns.tolist())

df.head()

# STEP 4: Add basic metadata from the filenames

df["filing_date"] = df["file_name"].str.extract(r"(\d{4}-\d{2}-\d{2})")
df["filing_type"] = df["file_name"].str.extract(r"_(424H)\.htm$")

# Everything before the date is the deal name
df["deal_name"] = df["file_name"].str.replace(
    r"_\d{4}-\d{2}-\d{2}_424H\.htm$",
    "",
    regex=True
).str.replace("_", " ")

print("Metadata added!")
df[["deal_name", "filing_date", "filing_type", "file_name"]].head()

# STEP 5: Check the manifest file

manifest_path = '/content/drive/MyDrive/manifest.csv'

manifest = pd.read_csv(manifest_path)

print("Manifest rows:", len(manifest))
print("Manifest columns:")
print(manifest.columns.tolist())

manifest.head()

# STEP 6: Match our downloaded files to the SEC manifest

# Create the same filename format used in our HTM folder
manifest["file_name"] = (
    manifest["entity_name"].str.replace(" ", "_")
    + "_"
    + manifest["filing_date"]
    + "_"
    + manifest["form"]
    + ".htm"
)

# Match the manifest information to our 122 filings
df = df.merge(
    manifest[
        ["file_name", "entity_name", "cik", "form", "filing_date",
         "accession", "primary_doc", "doc_url"]
    ],
    on="file_name",
    how="left",
    suffixes=("", "_manifest")
)

print("Rows in our index:", len(df))
print("SEC metadata matched:", df["cik"].notna().sum())

df[[
    "file_name",
    "deal_name",
    "filing_date",
    "cik",
    "accession",
    "primary_doc"
]].head()

# STEP 7: Fix the index and keep exactly our 122 downloaded filings

# Rebuild our original 122-file index
df = pd.DataFrame(data)

# Add our filename-based metadata again
df["filing_date"] = df["file_name"].str.extract(r"(\d{4}-\d{2}-\d{2})")
df["filing_type"] = df["file_name"].str.extract(r"_(424H)\.htm$")

df["deal_name"] = df["file_name"].str.replace(
    r"_\d{4}-\d{2}-\d{2}_424H\.htm$",
    "",
    regex=True
).str.replace("_", " ")

# Create filenames in the manifest
manifest["file_name"] = (
    manifest["entity_name"].str.replace(" ", "_")
    + "_"
    + manifest["filing_date"]
    + "_"
    + manifest["form"]
    + ".htm"
)

# Remove duplicate manifest filenames
manifest_unique = manifest.drop_duplicates("file_name")

# Add SEC metadata
df = df.merge(
    manifest_unique[
        ["file_name", "cik", "accession", "primary_doc", "doc_url"]
    ],
    on="file_name",
    how="left"
)

print("Final number of filings:", len(df))
print("SEC metadata matched:", df["cik"].notna().sum())

df[[
    "file_name",
    "deal_name",
    "filing_date",
    "filing_type",
    "cik",
    "accession"
]].head()

# STEP 8: Save our index to Google Drive

output_path = '/content/drive/MyDrive/abs_index.csv'

df.to_csv(output_path, index=False)

print("Saved!")
print(output_path)
print("Number of filings saved:", len(df))

# STEP 10: Check related words

for keyword in ["physical", "custody", "custodian", "paper"]:
    results = df[
        df["extracted_text"].str.contains(
            keyword,
            case=False,
            na=False
        )
    ]

    print(keyword, "->", len(results), "filings")